CREATE_TABLE = 'CREATE TABLE IF NOT EXISTS %s (%s);'
DROP_TABLE = 'DROP TABLE %s;'

SELECT_ALL = 'SELECT %s FROM %s;'
SELECT = 'SELECT %s FROM %s WHERE %s;'

INSERT_COLUMNS = 'INSERT INTO %s (%s) VALUES (%s);'

UPDATE = 'UPDATE %s SET %s WHERE %s;'
UPDATE_ALL = 'UPDATE %s SET %s;'

